'''
Works under the assumption that the file structure generated by phases 1 to 5 have not changed
'''

import argparse
import os
import sys
import time
import WrapperComparisonJob

'''Sample Run Command:
python WrapperComparisonMain.py --output-path /Users/robert/Desktop/outputs --experiment-name test1
'''

def main(argv):
    # Parse arguments
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('--output-path', dest='output_path', type=str, help='path to output directory')
    parser.add_argument('--experiment-name', dest='experiment_name', type=str, help='name of experiment (no spaces)')

    options = parser.parse_args(argv[1:])
    output_path = options.output_path
    experiment_name = options.experiment_name

    submitLocalJob(output_path+'/'+experiment_name)
    #submitClusterJob(output_path+'/'+experiment_name)

def submitLocalJob(experiment_path):
    WrapperComparisonJob.job(experiment_path)

def submitClusterJob(experiment_path):
    job_ref = str(time.time())
    job_name = experiment_path + '/jobs/' + job_ref + '_run.sh'
    sh_file = open(job_name, 'w')
    sh_file.write('#!/bin/bash\n')
    sh_file.write('#BSUB -J ' + job_ref + '\n')
    sh_file.write('#BSUB -o ' + experiment_path + '/logs/' + job_ref + '.o\n')
    sh_file.write('#BSUB -e ' + experiment_path + '/logs/' + job_ref + '.e\n')

    this_file_path = os.path.dirname(os.path.realpath(__file__))
    sh_file.write('python ' + this_file_path + '/WrapperComparisonJob.py ' + experiment_path + '\n')
    sh_file.close()
    os.system('bsub < ' + job_name)
    pass

if __name__ == '__main__':
    sys.exit(main(sys.argv))